services:
  - type: web
    name: slot-game
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn slot.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 